# Site settings
title: Escuelas Bosque Latinoamerica
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Inicitaiva que promueve el modelo pedagógico internacional del Aprendizaje en la Naturaleza en América Latina. También conocido como Escuelas Bosque o Bosquescuelas.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://escuelabosque.org/" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
